import { NextRequest, NextResponse } from 'next/server';
import * as cheerio from 'cheerio';
import TurndownService from 'turndown';

const turndownService = new TurndownService({
  headingStyle: 'atx',
  codeBlockStyle: 'fenced',
});

// Remove unnecessary elements from the HTML before converting to Markdown
function cleanHtml(html: string) {
  const $ = cheerio.load(html);
  $('script, style, nav, footer, header, aside, .sidebar, .nav, .footer, .header, .ad, .advertisement, svg, button, noscript').remove();
  
  // Try to find the most relevant content
  const contentSelector = 'main, article, .content, #content, .markdown, .documentation-content, .prose';
  const mainContent = $(contentSelector).first();
  
  if (mainContent.length > 0) {
    return mainContent.html() || '';
  }
  
  return $('body').html() || '';
}

export async function POST(req: NextRequest) {
  try {
    const { url } = await req.json();

    if (!url) {
      return NextResponse.json({ error: 'URL is required' }, { status: 400 });
    }

    let normalizedUrl = url;
    if (!url.startsWith('http')) {
      normalizedUrl = `https://${url}`;
    }

    const baseUrl = new URL(normalizedUrl);
    const visited = new Set<string>();
    const queue = [normalizedUrl];
    const results: { title: string; content: string; url: string }[] = [];

    const MAX_PAGES = 50;
    const CONCURRENCY = 5;

    while (queue.length > 0 && visited.size < MAX_PAGES) {
      // Process in batches for concurrency
      const batch = queue.splice(0, Math.min(CONCURRENCY, MAX_PAGES - visited.size));
      
      const batchPromises = batch.map(async (currentUrl) => {
        if (visited.has(currentUrl)) return null;
        visited.add(currentUrl);

        try {
          const response = await fetch(currentUrl, {
            headers: {
              'User-Agent': 'DocScraper-AI/1.0 (context builder for coding agents)',
            },
            next: { revalidate: 3600 }
          });
          
          if (!response.ok) return null;

          const html = await response.text();
          const $ = cheerio.load(html);

          const title = $('h1').first().text() || $('title').text() || currentUrl;
          const cleanedHtml = cleanHtml(html);
          const markdown = turndownService.turndown(cleanedHtml);

          // Find more links
          $('a[href]').each((_, el) => {
            const href = $(el).attr('href');
            if (!href) return;

            try {
              const absoluteUrl = new URL(href, currentUrl).href.split('#')[0]; // Remove hash
              const parsedAbsolute = new URL(absoluteUrl);

              if (
                parsedAbsolute.origin === baseUrl.origin &&
                parsedAbsolute.pathname.startsWith(baseUrl.pathname) &&
                !visited.has(absoluteUrl) &&
                !queue.includes(absoluteUrl) &&
                !batch.includes(absoluteUrl)
              ) {
                if (!absoluteUrl.match(/\.(png|jpg|jpeg|gif|pdf|zip|svg|mp4|webm|webp|css|js)$/i)) {
                  queue.push(absoluteUrl);
                }
              }
            } catch (e) {}
          });

          return { title, content: markdown, url: currentUrl };
        } catch (err) {
          console.error(`Error scraping ${currentUrl}:`, err);
          return null;
        }
      });

      const batchResults = await Promise.all(batchPromises);
      batchResults.forEach(res => {
        if (res) results.push(res);
      });
    }

    // Compile results
    let compiledMarkdown = `# Documentation Index: ${baseUrl.hostname}\n\n`;
    compiledMarkdown += `Generated by DocScraper AI on ${new Date().toLocaleDateString()}\n`;
    compiledMarkdown += `Base URL: ${url}\n\n`;
    
    compiledMarkdown += `## Table of Contents\n\n`;
    results.forEach((res, i) => {
      const anchor = res.title.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
      compiledMarkdown += `${i + 1}. [${res.title}](#${anchor})\n`;
    });
    
    compiledMarkdown += `\n---\n\n`;

    results.forEach((res) => {
      const anchor = res.title.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
      compiledMarkdown += `### ${res.title} <a name="${anchor}"></a>\n`;
      compiledMarkdown += `Source: ${res.url}\n\n`;
      compiledMarkdown += `${res.content}\n\n`;
      compiledMarkdown += `---\n\n`;
    });

    return NextResponse.json({ 
      markdown: compiledMarkdown, 
      pageCount: results.length 
    });
  } catch (error: any) {
    console.error('Scraping error:', error);
    return NextResponse.json({ error: error.message || 'Failed to scrape documentation' }, { status: 500 });
  }
}
